# Generated by Django 3.1.7 on 2021-04-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_in_lesson', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1)),
                ('grade_level', models.CharField(choices=[('K-6', 'K-6'), ('7-8', '7-8'), ('8-12', '8-12')], default='K-6', max_length=30)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social_Studies', 'Social Studies'), ('English', 'English'), ('Other', 'Other')], default='Math', max_length=30)),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_content', models.TextField()),
                ('lesson_goals', models.TextField()),
                ('lesson_class_introduction', models.TextField()),
                ('location_day_one', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Math', max_length=30)),
                ('lesson_day_one_description', models.TextField()),
                ('day_one_url_1', models.CharField(max_length=256)),
                ('day_one_url_2', models.CharField(max_length=256)),
                ('day_one_url_3', models.CharField(max_length=256)),
                ('day_one_url_4', models.CharField(max_length=256)),
                ('location_day_two', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Math', max_length=30)),
                ('lesson_day_two_description', models.TextField()),
                ('day_two_url_1', models.CharField(max_length=256)),
                ('day_two_url_2', models.CharField(max_length=256)),
                ('day_two_url_3', models.CharField(max_length=256)),
                ('day_two_url_4', models.CharField(max_length=256)),
                ('location_day_three', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Math', max_length=30)),
                ('lesson_day_three_description', models.TextField()),
                ('day_three_url_1', models.CharField(max_length=256)),
                ('day_three_url_2', models.CharField(max_length=256)),
                ('day_three_url_3', models.CharField(max_length=256)),
                ('day_three_url_4', models.CharField(max_length=256)),
                ('location_day_four', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Math', max_length=30)),
                ('lesson_day_four_description', models.TextField()),
                ('day_four_url_1', models.CharField(max_length=256)),
                ('day_four_url_2', models.CharField(max_length=256)),
                ('day_four_url_3', models.CharField(max_length=256)),
                ('day_four_url_4', models.CharField(max_length=256)),
                ('location_day_five', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Math', max_length=30)),
                ('lesson_day_five_description', models.TextField()),
                ('day_five_url_1', models.CharField(max_length=256)),
                ('day_five_url_2', models.CharField(max_length=256)),
                ('day_five_url_3', models.CharField(max_length=256)),
                ('day_five_url_4', models.CharField(max_length=256)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
